# Generated by Django 4.2.11 on 2024-03-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_one', models.IntegerField()),
                ('number_two', models.IntegerField()),
                ('summa', models.IntegerField()),
            ],
        ),
    ]
