# Generated by Django 4.2.11 on 2024-03-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattemain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbermodel',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='numbermodel',
            name='svarat',
            field=models.BooleanField(default=False),
        ),
    ]
